### ISSUE TITLE
allow_migrate returns True by default

### ISSUE THREAD

**Issue by AcckiyGerman** [mavriq/django-dbrouter#1]
Your docs says 
```python
# False - disable migrations
# True - do not disable migrations
# None - default
```
But if user won't specify `'allow_migrate'` in the config, this 
https://github.com/mavriq/django-dbrouter/blob/f8b15e3295fb8c2263131bbd5b8c1bd146b9e0ca/dbrouter/restrict_migrations.py#L44
will return `True`, isn't it ?
```bash
python3
>>> {}.get('allow_migrate', True)
True
```

## solution
`return settings.DATABASES[db].get('allow_migrate')` will return None by default

**Comment by mavriq** [comment]
I agree.
